docs(readme): add note for lit to use caseSesitive
cfware/babel-plugin-template-html-minifier pull request #20
Opened 2019-04-15 19:19 UTC by shaman-apprentice

closes #11 

I think adding a note should do fine. It's just a proposal - feel very free to adjust as you think how it will fit best :)

2019-04-15 20:02 UTC, coreyfarrell requested changes
I think these notes should not be collapsed / hidden, just show them.

@LarsDenBakker do you have any other comments?

2019-04-16 05:39 UTC, LarsDenBakker commented
Thats the only issue I found with lit so far, so should be good.

2019-04-16 20:22 UTC, coreyfarrell approved these changes

2019-04-16 20:22 UTC, merged

2019-04-16 20:24 UTC, coreyfarrell commented
@shaman-apprentice thanks for this docs update, merged!